services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zeroagency
    ports:
      - 5432:5432

volumes:
  db: